[[repo]]
    org = "mozilla-mobile"
    name = "android-components"
    branch = "master"

[[repo]]
    org = "mozilla-mobile"
    name = "fenix"
    branch = "master"

[[repo]]
    org = "mozilla-lockwise"
    name = "lockwise-android"
    branch = "master"

[[repo]]
    org = "mozilla-mobile"
    name = "focus-android"
    branch = "master"

