[[repo]]
    org = "mozilla-mobile"
    name = "android-components"
    branch = "main"

[[repo]]
    org = "mozilla-mobile"
    name = "fenix"
    branch = "main"

[[repo]]
    org = "mozilla-mobile"
    name = "focus-android"
    branch = "main"

[[repo]]
    org = "mozilla-mobile"
    name = "firefox-android"
    branch = "ac-prep"
