basepath = "."

[[includes]]
    path = "MozillaReality/FirefoxReality/l10n.toml"

[[includes]]
    path = "mozilla-lockwise/lockwise-android/l10n.toml"

[[includes]]
    path = "mozilla-mobile/android-components/l10n.toml"

[[includes]]
    path = "mozilla-mobile/fenix/l10n.toml"

[[includes]]
    path = "mozilla-mobile/firefox-tv/l10n.toml"
