name: Import Focus
on:
  schedule:
    - cron: "10 15 * * 1-5"
  workflow_dispatch:
jobs:
  copy:
    name: Import strings
    runs-on: ubuntu-latest
    steps:
      - name: Clone android-l10n repository
        uses: actions/checkout@v4
        with:
          path: l10n
      - name: Clone gecko-dev repository
        uses: actions/checkout@v4
        with:
          repository: mozilla/gecko-dev
          path: source
          sparse-checkout: |
            mobile/android/focus-android
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          pip install -r l10n/.github/requirements.txt
      - name: Copy source files
        run: >
          python l10n/.github/scripts/import_strings.py source
          --toml source/mobile/android/focus-android/l10n.toml
          --dest l10n/mozilla-mobile/focus-android
      - name: Update linter exceptions
        run: >
          python l10n/.github/scripts/update_config.py
          --toml l10n/focus.toml
          --config l10n/.github/scripts/linter_config.json
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ANDROID_GITHUB_TOKEN }}
          path: l10n
          branch: focus_l10n_updates
          author: l10n-bot <actions@users.noreply.github.com>
          commit-message: "Import focus quarantine"
          title: "Import focus quarantine"
          body: "Import focus quarantine"
          labels: l10n-bot
